# Teamplating is generating dynamic contents
-
  name: Test Jinja2 Templating
  hosts: localhost
  vars:
    first_name: james
    last_name: bond
  tasks:
  - debug:
      msg: 'The name is {{ last_name }}! {{ first_name }} {{ last_name }}!'

# To print the name in title case

tasks:
  - debug:
      msg: 'The name is {{ last_name | title }}! {{ first_name | title }} {{ last_name | title }}!'

# Lowest in array of numbers

-
  name: Test Jinja2 Templating
  hosts: localhost
  vars:
    array_of_numbers:
      - 12
      - 34
      - 06
      - 34
  tasks:
  - debug:
      msg: 'Lowest = {{array_of_numbers | min}} '

# Unique items among two lists

-
  name: Install Dependencies
  hosts: localhost
  vars:
    web_dependencies:
         - python
         - python-setuptools
         - python-dev
         - build-essential
         - python-pip
         - python-mysqldb
    sql_dependencies:
         - python
         - python-mysqldb
  tasks:
  - name: Install dependencies
    apt: name='{{ item }}' state=installed
    with_items: '{{ sql_dependencies | union(web_dependencies) }}'

# To generate random file name

-
  name: Generate random file name
  hosts: localhost
  tasks:
  - name: Create file
    file:
      path: /tmp/random_file"{{ 1000 | random }}"
      state: touch

# To check if ip address is valid

-
  name: Test valid IP Address
  hosts: localhost
  vars:
    ip_address: 192.168.1.6
  tasks:
  - name: Test IP Address
    debug:
      msg: IP Address = {{ ip_address | ipaddr }}
      
#  To retrieve file name from the path

-
  name: Get filename
  hosts: localhost
  vars:
    file_path: /etc/hosts
  tasks:
  - name: Get filename
    debug:
      msg: File Name = {{file_path | basename }}
