# Instead of storing the credentials in inventory file, we can store the
# credentials in any other file like csv,tsv,ini and use lookup function
# to look for the values

# CSV file
-
  name: Test Connectivity
  hosts: web_server
  vars:
    ansible_ssh_pass: "{{ lookup('csvfile', 'web_server file=credentials.csv delimiter=,') }}"
  tasks:
  - name: Ping target host
    ping:
      data: "Test"

# INI file 
-
  name: Test Connectivity
  hosts: web_server
  vars:
    ansible_ssh_pass: "{{ lookup('ini', 'password section=web_server file=credentials.ini') }}"
  tasks:
  - name: Ping target host
    ping:
      data: "Test"
